### ISSUE TITLE
README tasksCreate() misleading function signature

### ISSUE THREAD

**Issue by glenselle** [iron-io/iron_worker_node#6]
The README has sample code to queue a task like so:

```
ironWorker.tasksCreate('Windmill');
```

But when I do that, it actually creates the task and then throws an exception in the callback because `cb` doesn't exist (since the example doesn't pass a callback function). Here's the error--it's being thrown by client.js:

```
TypeError: undefined is not a function
at /Users/glenselle/Git Repositories/Chameleon/node_modules/iron_worker/lib/client.js:95:18
at APIClient.Client.parseResponse (/Users/glenselle/Git Repositories/Chameleon/node_modules/iron_worker/node_modules/iron_core/lib/client.js:244:16)
at /Users/glenselle/Git Repositories/Chameleon/node_modules/iron_worker/lib/api_client.js:114:16
at Request._callback (/Users/glenselle/Git Repositories/Chameleon/node_modules/iron_worker/node_modules/iron_core/lib/client.js:174:18)
at Request.self.callback (/Users/glenselle/Git Repositories/Chameleon/node_modules/iron_worker/node_modules/iron_core/node_modules/request/index.js:148:22)
at Request.EventEmitter.emit (events.js:98:17)
at Request.<anonymous> (/Users/glenselle/Git Repositories/Chameleon/node_modules/iron_worker/node_modules/iron_core/node_modules/request/index.js:876:14)
at Request.EventEmitter.emit (events.js:117:20)
at IncomingMessage.<anonymous> (/Users/glenselle/Git Repositories/Chameleon/node_modules/iron_worker/node_modules/iron_core/node_modules/request/index.js:827:12)
at IncomingMessage.EventEmitter.emit (events.js:117:20)
```

Which is caused by these lines in client.js:

```
// Since I'm only passing codeName and not params, options or cb, the code breaks later in the callback
Client.prototype.tasksCreate = function(codeName, params, options, cb) {
  var payload;
  payload = '';
  if (typeof params === 'string') {
    payload = params;
  } else {
    payload = JSON.stringify(params);
  }
  return this.api.tasksCreate(codeName, payload, options, function(error, body) {
    if (!(error != null)) {
      // This breaks because cb is undefined--I never pass a callback
      return cb(error, body.tasks[0]);
    } else {
      // And this also breaks because cb is undefined--I never pass a callback
      return cb(error, body);
    }
  });
};
```

So I'm wondering if the README once was accurate in that the code actually handled an `undefined` callback, or if this is a mistake. Since I only care about the name of the code package, I'm currently doing this so that I don't get exceptions thrown:

```
iron.worker.tasksCreate('Windmill', {}, {}, function(err, body) { });
```

Which is pretty clumsy considering JS's support of optional arguments. Anyway, if you want, I'd be willing to put together a pull request to support optional arguments so the callback function would be optional. Or at the least, update the README so it doesn't lead people to write code that throws exceptions.

**Comment by pcullin-ratio** [comment]
This tripped me up as well just now. Excluding options and a callback from tasksCreate will result in a false positive where the worker task gets queued successfully but the method execution fails with `undefined` exception since there's no callback. Please add proper method overload(s) to tasksCreate, or at the least update the documentation to make this clear.

**Comment by alex-litvak** [comment]
Thank you @glenselle!
Fixed in https://github.com/iron-io/iron_worker_node/pull/25
